### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Cheeeeer6** [Cheeeeer6/furima_28411#15]
# URL
https://furima-28411.herokuapp.com/

# Basic認証情報
ユーザー名：admin
パスワード：2222

# 出品者情報
Eメールアドレス：mikan@gmail.com
パスワード：mikan555

# 購入者情報
Eメールアドレス：yukidaruma@gmail.com
パスワード：yukidaruma555

# テストカード情報
カード番号：4242424242424242
有効期限：12/24
cvc：123

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○商品詳細に商品の説明が表示されていない為、表示させましょう。**

**○企業への提出物であり生き物は商品になじまない為、ぬいぐるみであれば「〜のぬいぐるみ」と入れていただいた方が良いように感じました。また、実際のフリマアプリに出品されているような洋服や雑貨等を出品商品にすると、よりリアルなアプリに仕上がるように思います。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Cheeeeer6** [comment]
挙動確認ありがとうございます！
ご指摘の箇所を修正しました
よろしくお願いします

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！　素敵に仕上がっていますね(^^)
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
